GO

/****** Object:  StoredProcedure [dbo].[SP_ResetAccounting]    Script Date: 05-04-2022 11:08:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER proc [dbo].[SP_ResetAccounting]
(
@CompanyID varchar(36)
)
AS
BEGIN
	DELETE [LMA Accounts Payable Check Payment Detail Current] WHERE CompanyID = @CompanyID
	DELETE [LMA Accounts Payable Check Transaction File] WHERE CompanyID = @CompanyID
	DELETE [LMA Accounts Payable Check Transaction History] WHERE CompanyID = @CompanyID
	DELETE [LMA Accounts Payable Invoice Footer History] WHERE CompanyID = @CompanyID
	DELETE [LMA Accounts Payable Invoice Header History] WHERE CompanyID = @CompanyID
	DELETE [LMA Accounts Payable Transactions] WHERE CompanyID = @CompanyID
	DELETE [LMA Accounts Receivable Invoice Footer History] WHERE CompanyID = @CompanyID
	DELETE [LMA Accounts Receivable Invoice Header History] WHERE CompanyID = @CompanyID
	DELETE [LMA Accounts Receivable Payment Detail] WHERE CompanyID = @CompanyID
	DELETE [LMA Accounts Receivable Transactions] WHERE CompanyID = @CompanyID
	DELETE [LMA Check Register Setup] WHERE CompanyID = @CompanyID
	DELETE [LMA General Journal Transaction Footer] WHERE CompanyID = @CompanyID
	DELETE [LMA General Journal Transaction Header] WHERE CompanyID = @CompanyID
	DELETE [LMA General Ledger Balance Sheet Setup] WHERE CompanyID = @CompanyID
	DELETE [LMA General Ledger Chart of Accounts] WHERE CompanyID = @CompanyID
	DELETE [LMA General Ledger Dept] WHERE CompanyID = @CompanyID
	DELETE [LMA General Ledger Income Statement Setup] WHERE CompanyID = @CompanyID
	DELETE [LMA General Ledger Transactions] WHERE CompanyID = @CompanyID
	DELETE [LMA System Config] WHERE CompanyID = @CompanyID
	DELETE [LMA UpdateLog] WHERE CompanyID = @CompanyID
	DELETE [LMA System Terms] WHERE CompanyID = @CompanyID
	DELETE [LMA Vendors] WHERE CompanyID = @CompanyID
	
	INSERT INTO [dbo].[LMA General Ledger Chart of Accounts]
        ([CompanyID]
        ,[GL_ACCT]
        ,[Description]
        ,[TYPE_CODE]
        ,[TYPE_DESCRIPTION]
        ,[CREDIT_DEBIT]
        ,[NON_CASH]
        ,[OPEN_CURRENT]
        ,[JAN_CURRENT]
        ,[FEB_CURRENT]
        ,[MAR_CURRENT]
        ,[APR_CURRENT]
        ,[MAY_CURRENT]
        ,[JUN_CURRENT]
        ,[JUL_CURRENT]
        ,[AUG_CURRENT]
        ,[SEP_CURRENT]
        ,[OCT_CURRENT]
        ,[NOV_CURRENT]
        ,[DEC_CURRENT]
        ,[END_CURRENT]
        ,[OPEN_1YR]
        ,[JAN_1YR]
        ,[FEB_1YR]
        ,[MAR_1YR]
        ,[APR_1YR]
        ,[MAY_1YR]
        ,[JUN_1YR]
        ,[JUL_1YR]
        ,[AUG_1YR]
        ,[SEP_1YR]
        ,[OCT_1YR]
        ,[NOV_1YR]
        ,[DEC_1YR]
        ,[END_1YR]
        ,[OPEN_2YR]
        ,[JAN_2YR]
        ,[FEB_2YR]
        ,[MAR_2YR]
        ,[APR_2YR]
        ,[MAY_2YR]
        ,[JUN_2YR]
        ,[JUL_2YR]
        ,[AUG_2YR]
        ,[SEP_2YR]
        ,[OCT_2YR]
        ,[NOV_2YR]
        ,[DEC_2YR]
        ,[END_2YR]
        ,[OPEN_BUDGET]
        ,[JAN_BUDGET]
        ,[FEB_BUDGET]
        ,[MAR_BUDGET]
        ,[APR_BUDGET]
        ,[MAY_BUDGET]
        ,[JUN_BUDGET]
        ,[JUL_BUDGET]
        ,[AUG_BUDGET]
        ,[SEP_BUDGET]
        ,[OCT_BUDGET]
        ,[NOV_BUDGET]
        ,[DEC_BUDGET]
        ,[END_BUDGET])
    SELECT @CompanyID
        ,[GL_ACCT]
        ,[Description]
        ,[TYPE_CODE]
        ,[TYPE_DESCRIPTION]
        ,[CREDIT_DEBIT]
        ,[NON_CASH]
        ,[OPEN_CURRENT]
        ,[JAN_CURRENT]
        ,[FEB_CURRENT]
        ,[MAR_CURRENT]
        ,[APR_CURRENT]
        ,[MAY_CURRENT]
        ,[JUN_CURRENT]
        ,[JUL_CURRENT]
        ,[AUG_CURRENT]
        ,[SEP_CURRENT]
        ,[OCT_CURRENT]
        ,[NOV_CURRENT]
        ,[DEC_CURRENT]
        ,[END_CURRENT]
        ,[OPEN_1YR]
        ,[JAN_1YR]
        ,[FEB_1YR]
        ,[MAR_1YR]
        ,[APR_1YR]
        ,[MAY_1YR]
        ,[JUN_1YR]
        ,[JUL_1YR]
        ,[AUG_1YR]
        ,[SEP_1YR]
        ,[OCT_1YR]
        ,[NOV_1YR]
        ,[DEC_1YR]
        ,[END_1YR]
        ,[OPEN_2YR]
        ,[JAN_2YR]
        ,[FEB_2YR]
        ,[MAR_2YR]
        ,[APR_2YR]
        ,[MAY_2YR]
        ,[JUN_2YR]
        ,[JUL_2YR]
        ,[AUG_2YR]
        ,[SEP_2YR]
        ,[OCT_2YR]
        ,[NOV_2YR]
        ,[DEC_2YR]
        ,[END_2YR]
        ,[OPEN_BUDGET]
        ,[JAN_BUDGET]
        ,[FEB_BUDGET]
        ,[MAR_BUDGET]
        ,[APR_BUDGET]
        ,[MAY_BUDGET]
        ,[JUN_BUDGET]
        ,[JUL_BUDGET]
        ,[AUG_BUDGET]
        ,[SEP_BUDGET]
        ,[OCT_BUDGET]
        ,[NOV_BUDGET]
        ,[DEC_BUDGET]
        ,[END_BUDGET] FROM [LoadManagerTemplate].[dbo].[LMA General Ledger Chart of Accounts]
	
	
	INSERT INTO [dbo].[LMA System Config]
        ([Next Invoice Number]
        ,[Next AR Voucher]
        ,[Next Sales Order Number]
        ,[Next Purchase Order Number]
        ,[Next AP Voucher]
        ,[Next GJ Number]
        ,[Next AR Recurring]
        ,[GL Transaction number]
        ,[Tax Rate]
        ,[Company Name]
        ,[Address1]
        ,[Address2]
        ,[City State Zip]
        ,[Phone]
        ,[Fax]
        ,[ARShip Via]
        ,[APShip Via]
        ,[AR Salesperson]
        ,[AR Entered by]
        ,[AR Taxable]
        ,[AR End Description]
        ,[AR Turn Off]
        ,[AR Print Ending Lines]
        ,[AP Print Ending Lines]
        ,[AP Entered BY]
        ,[AP Taxable]
        ,[AP End Description]
        ,[GL Clearing]
        ,[GL Clearing Dept]
        ,[AR GL Account]
        ,[AR GL Dept]
        ,[AR Discount GL]
        ,[AR Discount Dept GL]
        ,[AP GL Account]
        ,[AP GL Account Dept]
        ,[AP Discount GL]
        ,[AP Discount Dept GL]
        ,[AR Sales Tax Account]
        ,[AR Sales Tax Department]
        ,[AP Sales Tax Account]
        ,[AP Sales Tax Department]
        ,[AP Freight Account]
        ,[AP Freight Department]
        ,[GL Retain Account]
        ,[GL Retain Department]
        ,[Fiscal Year]
        ,[GL Current Earn Account]
        ,[GL Current Earn Deptartment]
        ,[AR Interest Earned Account]
        ,[AR Interest Earned Dept]
        ,[AR Freight Account]
        ,[AR Freight Department]
        ,[PO Not Invoiced Account]
        ,[PO Not Invoiced Dept]
        ,[AR Interest Rate]
        ,[AR Interest Days]
        ,[Auto Backorders]
        ,[Ready to Ship Default]
        ,[Invoice Paper]
        ,[PO Paper]
        ,[Statement Paper]
        ,[Company Info]
        ,[Interest_Interest]
        ,[Laser Checks]
        ,[AP Aging Period1]
        ,[AP Aging Period2]
        ,[AP Aging Period3]
        ,[AP Aging Period4]
        ,[AP Aging Period5]
        ,[AR Aging Period1]
        ,[AR Aging Period2]
        ,[AR Aging Period3]
        ,[AR Aging Period4]
        ,[AR Aging Period5]
        ,[Auto_Build]
        ,[Post]
        ,[Roll]
        ,[Labor]
        ,[Dunning]
        ,[Chk_clearing]
        ,[Chk_clearing_dept]
        ,[Int_acct]
        ,[Int_dept]
        ,[Chg_acct]
        ,[Chg_dept]
        ,[Bm_num]
        ,[Bm_glacct]
        ,[Bm_gldept]
        ,[Bm_auto]
        ,[Bm_post]
        ,[Bm_roll]
        ,[Bm_labor]
        ,[INVADJ_ACCT]
        ,[INVADJ_DEPT]
        ,[overshort acct]
        ,[overshort dept]
        ,[Security]
        ,[Company2]
        ,[Company3]
        ,[Company4]
        ,[Company5]
        ,[COMPANYLOGO]
        ,[PRINT LOGO]
        ,[tax_post]
        ,[NEXT RMA Number]
        ,[RMA Ending Lines]
        ,[PO Ending Description]
        ,[GL INCOME ACCOUNT]
        ,[GL INCOME DEPARTMENT]
        ,[out_sales_dept]
        ,[cust_deposit_dept]
        ,[Cust_Deposit_Acct]
        ,[GLEntry]
        ,[PODefaultReport]
        ,[POPostToGL]
        ,[Dunning Notice]
        ,[RegistrationNbr]
        ,[Used]
        ,[SOHowPostGL]
        ,[POOriginalRpt]
        ,[SOPrintSN]
        ,[SODisplaySN]
        ,[SOPostToGL]
        ,[APInvoiceHead]
        ,[SOTabBO]
        ,[SOTabDisc]
        ,[SOTabReqDate]
        ,[SOTabNotes]
        ,[SOTabSalesperson]
        ,[SOHideContract]
        ,[SOPrintReqDate]
        ,[ICDefClass]
        ,[APDefLookup]
        ,[ARDisplayRoute]
        ,[SMCompColor]
        ,[APCheckType]
        ,[ICClass]
        ,[ICDefLocation]
        ,[SODefFOB]
        ,[GLProcessDeposit]
        ,[ynEmail]
        ,[txtEMail]
        ,[txtEMailCC]
        ,[ynExportErrorLog]
        ,[txtErrorLogPath]
        ,[SOInvoiceRpt]
        ,[SOPrintAttn]
        ,[PODefCostDP]
        ,[PODefShipDate]
        ,[ARRecPymtSort]
        ,[ARDefOnFlyForm]
        ,[SOPackSlipWeight]
        ,[ARInvoicesToPrint]
        ,[SOSalesOrdersToPrint]
        ,[POPurchaseOrdersToPrint]
        ,[CurrentMonth]
        ,[PostingWindow]
        ,[POPrefix]
        ,[SOShowCOGS]
        ,[SOEditCOGS]
        ,[APShowReference]
        ,[APCheckStubType]
        ,[SOShowSkid]
        ,[ARCommInvSign]
        ,[ARInvoiceCategorySort]
        ,[ARInvoiceReceivedBy]
        ,[ARMarkupPercent]
        ,[ARUps]
        ,[SOInvoicePreprint]
        ,[ICInvGridAdjustNum]
        ,[ARShowZeroBalInvoice]
        ,[ICAvgCostAdjNum]
        ,[ICAvgCostAdjAcct]
        ,[GLFXAccount]
        ,[PayCommissionsOnPayment]
        ,[SOCommDefault]
        ,[ARPrintZeroBal]
        ,[UpdateLog]
        ,[Shipper Number]
        ,[APOmitZero]
        ,[SOEditSP]
        ,[POPrintLabels]
        ,[ICBarCodePrice]
        ,[ICProcurementBatchNum]
        ,[SODisplayUOM]
        ,[APCheckDupPO]
        ,[SOApplyDiscExt]
        ,[APReferenceSalesperson]
        ,[SODamageGoodsPrompt]
        ,[APInvoiceRemitAddress]
        ,[SOOutOfStock]
        ,[SODefaultQty]
        ,[SMspeed]
        ,[AllowCustomerChange]
        ,[CatchWeights]
        ,[MinimumCollectionBalance]
        ,[MinimumCollectionDays]
        ,[CompanyID]
        ,[AR Sales]
        ,[AR Cost of Sales]
        ,[UseDifferentGLAccountForCommodityTypes])
	SELECT
		[Next Invoice Number]
        ,[Next AR Voucher]
        ,[Next Sales Order Number]
        ,[Next Purchase Order Number]
        ,[Next AP Voucher]
        ,[Next GJ Number]
        ,[Next AR Recurring]
        ,[GL Transaction number]
        ,[Tax Rate]
        ,[Company Name]
        ,[Address1]
        ,[Address2]
        ,[City State Zip]
        ,[Phone]
        ,[Fax]
        ,[ARShip Via]
        ,[APShip Via]
        ,[AR Salesperson]
        ,[AR Entered by]
        ,[AR Taxable]
        ,[AR End Description]
        ,[AR Turn Off]
        ,[AR Print Ending Lines]
        ,[AP Print Ending Lines]
        ,[AP Entered BY]
        ,[AP Taxable]
        ,[AP End Description]
        ,[GL Clearing]
        ,[GL Clearing Dept]
        ,[AR GL Account]
        ,[AR GL Dept]
        ,[AR Discount GL]
        ,[AR Discount Dept GL]
        ,[AP GL Account]
        ,[AP GL Account Dept]
        ,[AP Discount GL]
        ,[AP Discount Dept GL]
        ,[AR Sales Tax Account]
        ,[AR Sales Tax Department]
        ,[AP Sales Tax Account]
        ,[AP Sales Tax Department]
        ,[AP Freight Account]
        ,[AP Freight Department]
        ,[GL Retain Account]
        ,[GL Retain Department]
        ,[Fiscal Year]
        ,[GL Current Earn Account]
        ,[GL Current Earn Deptartment]
        ,[AR Interest Earned Account]
        ,[AR Interest Earned Dept]
        ,[AR Freight Account]
        ,[AR Freight Department]
        ,[PO Not Invoiced Account]
        ,[PO Not Invoiced Dept]
        ,[AR Interest Rate]
        ,[AR Interest Days]
        ,[Auto Backorders]
        ,[Ready to Ship Default]
        ,[Invoice Paper]
        ,[PO Paper]
        ,[Statement Paper]
        ,[Company Info]
        ,[Interest_Interest]
        ,[Laser Checks]
        ,[AP Aging Period1]
        ,[AP Aging Period2]
        ,[AP Aging Period3]
        ,[AP Aging Period4]
        ,[AP Aging Period5]
        ,[AR Aging Period1]
        ,[AR Aging Period2]
        ,[AR Aging Period3]
        ,[AR Aging Period4]
        ,[AR Aging Period5]
        ,[Auto_Build]
        ,[Post]
        ,[Roll]
        ,[Labor]
        ,[Dunning]
        ,[Chk_clearing]
        ,[Chk_clearing_dept]
        ,[Int_acct]
        ,[Int_dept]
        ,[Chg_acct]
        ,[Chg_dept]
        ,[Bm_num]
        ,[Bm_glacct]
        ,[Bm_gldept]
        ,[Bm_auto]
        ,[Bm_post]
        ,[Bm_roll]
        ,[Bm_labor]
        ,[INVADJ_ACCT]
        ,[INVADJ_DEPT]
        ,[overshort acct]
        ,[overshort dept]
        ,[Security]
        ,[Company2]
        ,[Company3]
        ,[Company4]
        ,[Company5]
        ,[COMPANYLOGO]
        ,[PRINT LOGO]
        ,[tax_post]
        ,[NEXT RMA Number]
        ,[RMA Ending Lines]
        ,[PO Ending Description]
        ,[GL INCOME ACCOUNT]
        ,[GL INCOME DEPARTMENT]
        ,[out_sales_dept]
        ,[cust_deposit_dept]
        ,[Cust_Deposit_Acct]
        ,[GLEntry]
        ,[PODefaultReport]
        ,[POPostToGL]
        ,[Dunning Notice]
        ,[RegistrationNbr]
        ,[Used]
        ,[SOHowPostGL]
        ,[POOriginalRpt]
        ,[SOPrintSN]
        ,[SODisplaySN]
        ,[SOPostToGL]
        ,[APInvoiceHead]
        ,[SOTabBO]
        ,[SOTabDisc]
        ,[SOTabReqDate]
        ,[SOTabNotes]
        ,[SOTabSalesperson]
        ,[SOHideContract]
        ,[SOPrintReqDate]
        ,[ICDefClass]
        ,[APDefLookup]
        ,[ARDisplayRoute]
        ,[SMCompColor]
        ,[APCheckType]
        ,[ICClass]
        ,[ICDefLocation]
        ,[SODefFOB]
        ,[GLProcessDeposit]
        ,[ynEmail]
        ,[txtEMail]
        ,[txtEMailCC]
        ,[ynExportErrorLog]
        ,[txtErrorLogPath]
        ,[SOInvoiceRpt]
        ,[SOPrintAttn]
        ,[PODefCostDP]
        ,[PODefShipDate]
        ,[ARRecPymtSort]
        ,[ARDefOnFlyForm]
        ,[SOPackSlipWeight]
        ,[ARInvoicesToPrint]
        ,[SOSalesOrdersToPrint]
        ,[POPurchaseOrdersToPrint]
        ,[CurrentMonth]
        ,[PostingWindow]
        ,[POPrefix]
        ,[SOShowCOGS]
        ,[SOEditCOGS]
        ,[APShowReference]
        ,[APCheckStubType]
        ,[SOShowSkid]
        ,[ARCommInvSign]
        ,[ARInvoiceCategorySort]
        ,[ARInvoiceReceivedBy]
        ,[ARMarkupPercent]
        ,[ARUps]
        ,[SOInvoicePreprint]
        ,[ICInvGridAdjustNum]
        ,[ARShowZeroBalInvoice]
        ,[ICAvgCostAdjNum]
        ,[ICAvgCostAdjAcct]
        ,[GLFXAccount]
        ,[PayCommissionsOnPayment]
        ,[SOCommDefault]
        ,[ARPrintZeroBal]
        ,[UpdateLog]
        ,[Shipper Number]
        ,[APOmitZero]
        ,[SOEditSP]
        ,[POPrintLabels]
        ,[ICBarCodePrice]
        ,[ICProcurementBatchNum]
        ,[SODisplayUOM]
        ,[APCheckDupPO]
        ,[SOApplyDiscExt]
        ,[APReferenceSalesperson]
        ,[SODamageGoodsPrompt]
        ,[APInvoiceRemitAddress]
        ,[SOOutOfStock]
        ,[SODefaultQty]
        ,[SMspeed]
        ,[AllowCustomerChange]
        ,[CatchWeights]
        ,[MinimumCollectionBalance]
        ,[MinimumCollectionDays]
        ,@CompanyID
        ,[AR Sales]
        ,[AR Cost of Sales]
        ,[UseDifferentGLAccountForCommodityTypes] FROM [LoadManagerTemplate].[dbo].[LMA System Config]
	
	
	INSERT INTO [dbo].[LMA General Ledger Income Statement Setup]
        ([ProfitType]
        ,[MainSort]
        ,[MainTitle]
        ,[SubSort]
        ,[SubTitle]
        ,[GLAcctFrom]
        ,[GLAcctTo]
        ,[CompanyID])
	SELECT 
		[ProfitType]
        ,[MainSort]
        ,[MainTitle]
        ,[SubSort]
        ,[SubTitle]
        ,[GLAcctFrom]
        ,[GLAcctTo]
        ,@CompanyID FROM [LoadManagerTemplate].[dbo].[LMA General Ledger Income Statement Setup]

	
	INSERT INTO [dbo].[LMA General Ledger Balance Sheet Setup]
        ([ProfitType]
        ,[MainSort]
        ,[MainTitle]
        ,[SubSort]
        ,[SubTitle]
        ,[GLAcctFrom]
        ,[GLAcctTo]
        ,[CompanyID])
	SELECT
		[ProfitType]
        ,[MainSort]
        ,[MainTitle]
        ,[SubSort]
        ,[SubTitle]
        ,[GLAcctFrom]
        ,[GLAcctTo]
        ,@CompanyID FROM [LoadManagerTemplate].[dbo].[LMA General Ledger Balance Sheet Setup]
	
END
GO


